### ISSUE TITLE
change access_token_ttl only for client_credentials

### ISSUE THREAD

**Issue by gustvao** [trikoder/oauth2-bundle#105]
Is it possible to change the access_token_ttl only for client_credentials? I wanted to have different expirations for client_credentials and for password.

Tks

**Comment by gschafra** [comment]
Would be nice, if that would be possible. Also needed in my project.

Thanks in advance

**Comment by HypeMC** [comment]
@gustvao @gschafra Hi, apologies for the late answer, in short setting the ttl on a per grant level is currently not supported, but it's definitely a feature we would like to add in the future. Also, any PR is welcomed & greatly appreciated.

**Comment by florianajir** [comment]
Is there any event or something else to deal with custom ttl from authorized user property?
(I have to deal with account expiration with duration set in db)
