### ISSUE TITLE
Can't use refresh token

### ISSUE THREAD

**Issue by marvin-SL** [trikoder/oauth2-bundle#107]
Hello, 

I can have an access token with a  POST request to `/token`: 

```
{
"grant_type":"password",
"client_id":"myclientid",
"username":"john@doe.com",
"password":"foo",
"client_secret":"3d4a940.....3c1ea38b5"
}
```
And the response is : 

```
{
    "token_type": "Bearer",
    "expires_in": 60,
    "access_token": "eyJ0eXAi....nK0Ag",
    "refresh_token": "def50200dfce4da3....fdc689e5"
}
```

So far so good, and when the token expires after 60 secs, I send another POST request to `/token` : 

```
{
"grant_type":"refresh_token",
"client_id":"myclientid",
"client_secret":"3d4a940.....3c1ea38b5"
"refresh_token": "def50200dfce4da3....fdc689e5"
}
```

But it doesn't work and all i've got is : 

```
{
    "error": "invalid_client",
    "error_description": "Client authentication failed",
    "message": "Client authentication failed"
}
```

Can you tell me if I forgot something ? thanks
I'm using Postman for request, with `raw` and `application/json` checked

**Comment by TheGeniesis** [comment]
Hello,
I had the same problem.
I needed to add `access_token` to table `oauth2_client`, column `grants`.
Currently I generate client like this:
```
bin/console trikoder:oauth2:create-client example_id --grant-type client_credentials --grant-type password --grant-type refresh_token
```

**Comment by marvin-SL** [comment]
It works ! Thank you so much @TheGeniesis
