### ISSUE TITLE
Can't use authorization_code

### ISSUE THREAD

**Issue by marvin-SL** [trikoder/oauth2-bundle#108]
So after some research, I've found out `password` grant was not recommended for SPA or web browser client because of storage issue with the `secret`.
`authorization_code` is supported since #18 , I updated my `oauth2_client` table and granted  `authorization_code` to my client

```
curl -X GET \
  http://192.168.43.191:8000/authorize \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Postman-Token: ca83457e-18c9-4b7d-9a28-bfd4b9eaaa81' \
  -H 'cache-control: no-cache' \
  -d 'response_type=code&client_id=test&redirect_uri=www.google.com&state=zeaesd&scope=read%20create'
```

The response : 

```
{
    "error": "unsupported_grant_type",
    "error_description": "The authorization grant type is not supported by the authorization server.",
    "hint": "Check that all required parameters have been provided",
    "message": "The authorization grant type is not supported by the authorization server."
}
```
Do you know what I'm doing wrong ?

For the state, I just put random char, it's an optional parameter but I wonder how to generate a real one

Thanks

**Comment by X-Coder264** [comment]
@marvin-SL You are using the curl `-d` option for sending the needed info to the endpoint.

[-d is used for sending POST data](https://curl.haxx.se/docs/manpage.html#-d) while the AuthCodeGrant [checks if it supports the authorization request from the GET query parameters](https://github.com/thephpleague/oauth2-server/blob/7.4.0/src/Grant/AuthCodeGrant.php#L215).

**Comment by marvin-SL** [comment]
Sorry I did that when I generated the curl request from postman, but I'm sending a GET request in postman (symfony tells me that POST is not supported when I try ).
I'm going to edit 
thanks

**Comment by marvin-SL** [comment]
@X-Coder264 You were right, the request was not GET but POST, event if I choosed GET in postman :+1: 
Now I got :
```

{
    "error": "invalid_client",
    "error_description": "Client authentication failed",
    "message": "Client authentication failed"
}
```

```
curl -X GET \
  'http://192.168.43.191:8000/authorize?client_id=test&response_type=code' \
  -H 'Postman-Token: 178c598b-2593-4f59-84ef-27eeda14cece' \
  -H 'cache-control: no-cache'
```

**Comment by sebardo** [comment]
Hi Marvin,

Add client redirect uri and scope to your get params.

**Comment by marvin-SL** [comment]
@sebardo Correct i was missing parameters in the request AND the database.
I added the missing parameters + redirect_uri in the database and it seem to work now 

`http://192.168.43.191:8000/authorize?response_type=code&client_id=test&redirect_uri=https%3A%2F%2Fexample-app.com&scope=read+create&state=xcoiv98y2kd22vusuye3kch`

 im redirected to the page `https://example-app.com`, I guess this is where I have to put my real login page. Thank you @sebardo  and @X-Coder264 !
