### ISSUE TITLE
compatibility with symfony 4.4

### ISSUE THREAD

**Issue by gustvao** [trikoder/oauth2-bundle#112]
guys, I've been testing 4.4 and the bundle works almost seamlessly with it.

The only thing that appears that is not working is the firewall, in other words, regardless if you activate a route to pass only if authenticated, it ignores it and all routes are available for everyone.

Apart from that the remaining of the module (from what I tested) seems to be working, creating the token, client authentication 

just fyi given that symfony 4.4 is due this Friday

**Comment by ddlzz** [comment]
can you show your security.yaml config? I swithed to 4.4 too but didn't notice such issues

**Comment by gustvao** [comment]
I was using 4.4 beta. after the official release it seems to be working
close #112
