### ISSUE TITLE
[question] How to retrieve the user concerned by the token?

### ISSUE THREAD

**Issue by Skunkyman** [trikoder/oauth2-bundle#113]
Hello,
I need some help. I've followed all instructions to make the oauth2 flow works and it actually does. But i need to get the user with for example $tokenStorage->getToken()->getUser() or $this->getUser() but it returns me NULL while it arrives to resolve roles..
Is there any configuration I missed about userProvider or something similar?
Or at least, how to bind the client with some User?
Thanks by advance for your reply

Best regards,

Maxime D

**Comment by thePhrenologist** [comment]
You can probably use something like this @Skunkyman . I believe it's in the docs somewhere. If you want to use the code flow you need to implement something similar

services.yml
````
    App\EventListener\UserResolveListener:
        arguments:
            - '@fos_user.user_provider.username_email'
            - '@security.password_encoder'
        tags:
            - { name: kernel.event_listener, event: trikoder.oauth2.user_resolve, method: onUserResolve }

````

src/EventListener/UserResolveListener.php
````
<?php

declare(strict_types=1);

namespace App\EventListener;

use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Trikoder\Bundle\OAuth2Bundle\Event\UserResolveEvent;

final class UserResolveListener
{
    /**
     * @var UserProviderInterface
     */
    private $userProvider;

    /**
     * @var UserPasswordEncoderInterface
     */
    private $userPasswordEncoder;

    /**
     * @param UserProviderInterface $userProvider
     * @param UserPasswordEncoderInterface $userPasswordEncoder
     */
    public function __construct(UserProviderInterface $userProvider, UserPasswordEncoderInterface $userPasswordEncoder)
    {
        $this->userProvider = $userProvider;
        $this->userPasswordEncoder = $userPasswordEncoder;
    }

    /**
     * @param UserResolveEvent $event
     */
    public function onUserResolve(UserResolveEvent $event): void
    {
        $user = $this->userProvider->loadUserByUsername($event->getUsername());

        if (null === $user) {
            return;
        }

        if (!$this->userPasswordEncoder->isPasswordValid($user, $event->getPassword())) {
            return;
        }

        $event->setUser($user);
    }
}

**Comment by Skunkyman** [comment]
First, thank you for your reply.
I misexplained it.
In my case, I've got no "real user" but only an oauth client (no grant type password) with a grant type user_credentials. However, I need to add some configuration related to the user (which is here an oauth client).
So what I want:
  - bind a user to an oauth client but it's like I can't access the entity and found him with credentials.
  - the point is to give rights to the user to protect some content that scopes can't really protect as routes are the same, only thre request will change depending on the user.
The workaround I found is to manually create a user and give him the client credential (not even with a FK constraint...) and get him with credentials contains inside the token but I'm pretty much confident about the fact there's a really better way to achieve this.. If you've got any idea...

best regards,

Maxime D

**Comment by spideyfusion** [comment]
The `client_credentials` grant is meant to be used for machine-to-machine communication, which means that issued access tokens can't be bound to a user.

For your case, you'll have to manually query the user instead of grabbing it from the security token. Something along these lines:

```php
/** @var \Trikoder\Bundle\OAuth2Bundle\Security\Authentication\Token\OAuth2Token $token */
$token = $this->tokenStorage->getToken();

$clientId = $token->getAttribute('server_request')->getAttribute('oauth_client_id');

// Locate the user that we want to manipulate
$user = $this->userRepository->find($clientId);

// Make desired modifications...

$this->entityManager->persist($user);
$this->entityManager->flush();
```

Feel free to re-open the issue if you require more assistance.

**Comment by fishmandev** [comment]
If I use grant_type 'authorization_code', how can I get a logged in user entity in any controller?

**Comment by rl-Rahul** [comment]
> You can probably use something like this @Skunkyman . I believe it's in the docs somewhere. If you want to use the code flow you need to implement something similar
> 
> services.yml
> 
> ```
>     App\EventListener\UserResolveListener:
>         arguments:
>             - '@fos_user.user_provider.username_email'
>             - '@security.password_encoder'
>         tags:
>             - { name: kernel.event_listener, event: trikoder.oauth2.user_resolve, method: onUserResolve }
> ```
> 
> src/EventListener/UserResolveListener.php
> 
> ```
> <?php
> 
> declare(strict_types=1);
> 
> namespace App\EventListener;
> 
> use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
> use Symfony\Component\Security\Core\User\UserProviderInterface;
> use Trikoder\Bundle\OAuth2Bundle\Event\UserResolveEvent;
> 
> final class UserResolveListener
> {
>     /**
>      * @var UserProviderInterface
>      */
>     private $userProvider;
> 
>     /**
>      * @var UserPasswordEncoderInterface
>      */
>     private $userPasswordEncoder;
> 
>     /**
>      * @param UserProviderInterface $userProvider
>      * @param UserPasswordEncoderInterface $userPasswordEncoder
>      */
>     public function __construct(UserProviderInterface $userProvider, UserPasswordEncoderInterface $userPasswordEncoder)
>     {
>         $this->userProvider = $userProvider;
>         $this->userPasswordEncoder = $userPasswordEncoder;
>     }
> 
>     /**
>      * @param UserResolveEvent $event
>      */
>     public function onUserResolve(UserResolveEvent $event): void
>     {
>         $user = $this->userProvider->loadUserByUsername($event->getUsername());
> 
>         if (null === $user) {
>             return;
>         }
> 
>         if (!$this->userPasswordEncoder->isPasswordValid($user, $event->getPassword())) {
>             return;
>         }
> 
>         $event->setUser($user);
>     }
> }
> ```

I also had a similar issue with user retrieval from the concerned token. I implemented the `UserResolveListener` but still I am getting `NULL` while calling `$this->getUser()`. I am using Symfony 5.3 with grant types `client_credentials, password and refresh_token`. Please help me to fix it. Thanks in advance
