### ISSUE TITLE
Error with DependencyInjection Configuration when deploying app (PHP compatibility)

### ISSUE THREAD

**Issue by gonzaloplaza** [trikoder/oauth2-bundle#115]
Hi , we're getting this error when trying to deploy project using version 2.0.1 of this bundle:

---------
Symfony version : 4.2.11  
PHP version: 7.1.15
---------
12:50:38 PHP Fatal error:  Uncaught TypeError: Return value of Trikoder\Bundle\OAuth2Bundle\DependencyInjection\Configuration::getWrappedTreeBuilder() must be an instance of Trikoder\Bundle\OAuth2Bundle\DependencyInjection\object, instance of class@anonymous returned in  ..../vendor/trikoder/oauth2-bundle/DependencyInjection/Configuration.php:172

**Comment by spideyfusion** [comment]
As stated in the Composer metadata, the minimum required PHP version for using this bundle is 7.2.

**Comment by gonzaloplaza** [comment]
Thanks @spideyfusion , we know about it. However, as we tested recently, the unique detected conflict with PHP 7.1 is about this function and its returned type (currently is returning an anonymous class type: class@anonymous)

Trikoder\Bundle\OAuth2Bundle\DependencyInjection\Configuration (https://github.com/trikoder/oauth2-bundle/blob/v2.0.1/DependencyInjection/Configuration.php#L170)

`private function getWrappedTreeBuilder(string $name): object {`

Removing return type will work:

`private function getWrappedTreeBuilder(string $name) {`

**Comment by X-Coder264** [comment]
@gonzaloplaza Yes, that is because the object typehint was added in PHP 7.2.

The bundle does not support 7.1 as the active and now even the security support for it ended as can be seen on https://www.php.net/supported-versions.php.

So I'm closing this as we don't consider this to be an issue because the minimal version is properly stated in composer.json.
