### ISSUE TITLE
remove "final" keyword from classes and make properties protected

### ISSUE THREAD

**Issue by alyamovsky** [trikoder/oauth2-bundle#116]
hi! thanks for the great bundle

can you remove the "final" keyword from classes, especially from controllers? since code from a bundle should be customizable, it would be nice to be able to add some apidoc annotations for example

**Comment by spideyfusion** [comment]
Could you provide us with a couple of extension use cases so we can get a better idea on what you're trying to achieve? Certain classes are marked as `final` because they weren't designed with extending in mind.

**Comment by ddlzz** [comment]
of course, two first cases that coming to mind are:
1. to add some nelmio/apidoc annotations for controllers since our frontend devs will be using it
2. to set some decorator for the phpleague/oauth `AuthorizationServer` to be able to set the PKCE challenge for the auth code flow.
