### ISSUE TITLE
Symfony4.3  AuthorizationRequestResolveEvent::$authorizationResolution

### ISSUE THREAD

**Issue by lanrenbulan** [trikoder/oauth2-bundle#117]
AuthorizationRequestResolveEvent::getAuthorizationResolution(),  always return false.

I did not find a call to the resolveauthorization method.

Error: The resource owner or authorization server denied the request

**Comment by thePhrenologist** [comment]
you can do it yourself in a listener:

something like

````
/**
     * @param AuthorizationRequestResolveEvent $event
     */
    public function onUserResolve(AuthorizationRequestResolveEvent $event): void
    {
        $user = $event->getUser();
        if (null === $user) {
            return;
        }
        $event->resolveAuthorization(AuthorizationRequestResolveEvent::AUTHORIZATION_APPROVED);
    }

**Comment by lanrenbulan** [comment]
Is there a detailed document?

**Comment by ajgarlag** [comment]
@lanrenbulan You have to resolve the authorization writing a listener for the `AuthorizationRequestResolveEvent`. In this listener, you should call:
  - `$event->resolveAuthorization(true)` if you authorize the request.
  - `$event->resolveAuthorization(false)` if you do not authorize the request.
  - `$event->setResponse($usuallyARedirectionResponse)` if you want return a custom response to the user. This is usually a redirection to a page where the user can allow or deny the client request.

**Comment by ajgarlag** [comment]
@lanrenbulan You can see https://gist.github.com/ajgarlag/1f84d29ee0e1a92c8878f44a902338cd
