### ISSUE TITLE
I didn't get refresh Token In get token  response 

### ISSUE THREAD

**Issue by Amr3zzat** [trikoder/oauth2-bundle#119]
I am using client_credentials grant type , I put enable_refresh_token_grant: true in the settings , No refresh_token returned in the response ? How Can I refresh my token
the return json :
`{
    "token_type": "Bearer",
    "expires_in": 2592000,
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImE4ZmJkM2E5MzcxMGZkYzI1NzFhMmU4OGMxYmZlNDRkMDg1NzRlMDk0MDExY2M0ODRhNGI0NGVhNjA2NDY2OGU4MGViNTM0MDZlZmI1Zjg3In0.eyJhdWQiOiJBbXIiLCJqdGkiOiJhOGZiZDNhOTM3MTBmZGMyNTcxYTJlODhjMWJmZTQ0ZDA4NTc0ZTA5NDAxMWNjNDg0YTRiNDRlYTYwNjQ2NjhlODBlYjUzNDA2ZWZiNWY4NyIsImlhdCI6MTU3NDY5MDQzNCwibmJmIjoxNTc0NjkwNDM0LCJleHAiOjE1NzcyODI0MzQsInN1YiI6IiIsInNjb3BlcyI6W119.bp1IwTkpQLlVmsa27hGb1L2rg3SJwIu1oo3FLhMU5r2Ro7A5t9VBL3SYGn3aBA4yABVP1Gre9yiyqxdHr0hoOQ27uPLIzffa3uGRrRRgEG0NMQvHKVS8SY_-obdrNND8vTSeosTjSEzp7DY6wO-gn6NwSROSKTbNo8TDbhifCFFw8g-_p2EP8SAA8kmfMZAmx3Vk-c_pEmJlfscqJ7-iSd4SHfAjTsmWLeFgnujLOQlWX1iItQKWzbBxbKA2Zw9N9k54TPPzAIJHMf_7qCqHjtLd7cZlNSZ7jsXuMH2xYYHD6oZ6EmpYIF5CW5gIdaH4rA1UhorkZmzYa2_6M5lWwA"
}`

the settings 

`trikoder_oauth2:
  authorization_server:

    # How long the issued access token should be valid for.
    # The value should be a valid interval: http://php.net/manual/en/dateinterval.construct.php#refsect1-dateinterval.construct-parameters
    access_token_ttl: P1M

    # Whether to enable the client credentials grant
    enable_client_credentials_grant: true

    # Whether to enable the password grant
    enable_password_grant: true

    # Whether to enable the refresh token grant
    enable_refresh_token_grant: true

    # Whether to enable the authorization code grant
    enable_auth_code_grant: true

    # Whether to enable the implicit grant
    enable_implicit_grant: true
    private_key: '%kernel.project_dir%/var/private.key'
    encryption_key: '%env(string:OAUTH2_ENCRYPTION_KEY)%'   # (Optional) Change this

  resource_server:
    public_key: '%kernel.project_dir%/var/public.key'

  persistence:
    doctrine: null
`

What I should Do to refresh my token ?

**Comment by X-Coder264** [comment]
The `enable_refresh_token_grant` just enables the `refresh_token` grant. That does not mean that when getting a new access token via the `client_credentials` grant that you will get the refresh token.

The specification states that client credentials grant SHOULD NOT return a refresh token:
https://tools.ietf.org/html/rfc6749#section-4.4.3

To get a new token simply initiate another client credentials grant flow to the /token endpoint. There is no user interaction involved, so your application can do this at any time.

**Comment by Amr3zzat** [comment]
@X-Coder264  Thanks I got that.
