### ISSUE TITLE
Some deprecations in use

### ISSUE THREAD

**Issue by KorDum** [trikoder/oauth2-bundle#130]
From Symfony 4.4:
> The "Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent::getException()" method is deprecated since Symfony 4.4, use "getThrowable()" instead.

From Symfony 4.3:
> The "Trikoder\Bundle\OAuth2Bundle\Security\Firewall\OAuth2Listener" class implements "Symfony\Component\Security\Http\Firewall\ListenerInterface" that is deprecated since Symfony 4.3, turn listeners into callables instead.

**Comment by X-Coder264** [comment]
@KorDum We are aware of those deprecations, but we can't solve them in the current major version (2.x) as we are supporting Symfony 3.4 on v2 (we can't solve them without dropping support for Symfony 3.4). On v3 which will support Symfony 4.4 and Symfony 5.x those deprecations will be fixed.

**Comment by X-Coder264** [comment]
Closed by https://github.com/trikoder/oauth2-bundle/pull/150
