### ISSUE TITLE
Add ability to override persisters in different environment

### ISSUE THREAD

**Issue by miroslav-marinkovic** [trikoder/oauth2-bundle#14]
Currently, when you define `persisters` in `config.yml` (ie doctrine), and define a different one in  `config_test.yml` (ie in_memory), you end up having more than one persister in merged config. This is not supported and an exception is raised in `TrikoderOAuth2Extension::configurePersistence`.

**Comment by miroslav-marinkovic** [comment]
It works flawlessly!

**Comment by spideyfusion** [comment]
Fixed with https://github.com/trikoder/oauth2-bundle/pull/15.
