### ISSUE TITLE
Option to disable "plain" value for code_challenge_method

### ISSUE THREAD

**Issue by florianajir** [trikoder/oauth2-bundle#142]
There's no option to force `S256` value for `code_challenge_method` on `/authorize` endpoint

**Comment by X-Coder264** [comment]
There are no mentions about this in the [PKCE RFC](https://tools.ietf.org/html/rfc7636).

Do you have examples from other oauth2 server implementation libraries who do this?  I'm interested to know if there are any and if there are how does the error response look like in that case.

**Comment by florianajir** [comment]
https://tools.ietf.org/html/rfc7636#section-7.2

  

> 7.2.  Protection against Eavesdroppers
> 
>    Clients MUST NOT downgrade to "plain" after trying the "S256" method.
>    Servers that support PKCE are required to support "S256", and servers
>    that do not support PKCE will simply ignore the unknown
>    "code_verifier".  Because of this, an error when "S256" is presented
>    can only mean that the server is faulty or that a MITM attacker is
>    trying a downgrade attack.
> 
>    The "S256" method protects against eavesdroppers observing or
>    intercepting the "code_challenge", because the challenge cannot be
>    used without the verifier.  With the "plain" method, there is a
>    chance that "code_challenge" will be observed by the attacker on the
>    device or in the http request.  Since the code challenge is the same
>    as the code verifier in this case, the "plain" method does not
>    protect against the eavesdropping of the initial request.
> 
>    The use of "S256" protects against disclosure of the "code_verifier"
>    value to an attacker.
> 
>    Because of this, "plain" SHOULD NOT be used and exists only for
>    compatibility with deployed implementations where the request path is
>    already protected.  The "plain" method SHOULD NOT be used in new
>    implementations, unless they cannot support "S256" for some technical
>    reason.
> 
>    The "S256" code challenge method or other cryptographically secure
>    code challenge method extension SHOULD be used.  The "plain" code
>    challenge method relies on the operating system and transport
>    security not to disclose the request to an attacker.
> 
>    If the code challenge method is "plain" and the code challenge is to
>    be returned inside authorization "code" to achieve a stateless
>    server, it MUST be encrypted in such a manner that only the server
>    can decrypt and extract it.

**Comment by florianajir** [comment]
> Do you have examples from other oauth2 server implementation libraries who do this? I'm interested to know if there are any and if there are how does the error response look like in that case.

Why not simply a 400 error with message and hint ?

**Comment by X-Coder264** [comment]
@florianajir I am aware of the text you've pasted as it is from the RFC tha I've linked :smile: 

It doesn't say anything about servers forcing `S256` method. It only says that all servers must support `S256` and that clients must not downgrade to `plain`.

Since it doesn't say anything about it (nor do I see other oauth server implementations like Laravel Passport having this option) I don't feel like we should add our custom error response for this.

**Comment by florianajir** [comment]
> If the client is capable of using "S256", it MUST use "S256", as "S256" is Mandatory To Implement (MTI) on the server.

So why not adding a property on client to indicate if it supports s256 so make it mandatory ?

here few implementations:
https://learn.akamai.com/en-us/webhelp/identity-cloud/technical-library/GUID-8D75F172-ACD5-4BDA-B7BF-94D4F3A415EB.html

> Note: Hosted login requires the use of SHA256 to hash code verifiers. Although the PKCE standard allows for the use of plain-text code challenges, plain text is notsupported by hosted login. You can verify this by looking at the discovery document to see which code challenge methods are supported

https://github.com/IdentityServer/IdentityServer4/issues/381

**Comment by X-Coder264** [comment]
> > If the client is capable of using "S256", it MUST use "S256", as "S256" is Mandatory To Implement (MTI) on the server.
> 
> So why not adding a property on client to indicate if it supports s256 so make it mandatory ?

This is an oauth server, not client implementation.

**Comment by florianajir** [comment]
@X-Coder264 I talk about `oauth2_client table`

**Comment by X-Coder264** [comment]
@florianajir Oh, ok, I see what you mean. Thanks for the clarification.
