### ISSUE TITLE
Add a guard implementation

### ISSUE THREAD

**Issue by maddy2101** [trikoder/oauth2-bundle#144]
Hi,

I am currently integrating the bundle into a brand new symfony 4.4 project. I wish to protect a certain route with two authentication methods, being JWT Token and OAuth2 Token, depending on the requesting party.
For the JWT Token Auth I use package 'lexik/jwt-authentication-bundle`, which ships with an integrated Security Guard implementation that makes it very easy to add to a firewall section. Your package does not, but I think it would be a great enhancement.

**Comment by tomcoonen** [comment]
@spideyfusion Can we help to get this implemented?

**Comment by HypeMC** [comment]
@tomcoonen Hi, this is a feature we would definitely like to have but we haven't gotten around to it yet. If you are interested in helping to implement this feature, any contribution would be greatly appreciated.

**Comment by tomcoonen** [comment]
I’m working on a guard, so when it’s done you can expect a PR.

**Comment by videni** [comment]
@tomcoonen,  is your PR ready? thanks.

**Comment by wsmits** [comment]
@tomcoonen Have you already been able to create the Guard?
We have the same use case as @maddy2101 and would be very happy to see the Guard implemented.
Thanks.

**Comment by vbarrier** [comment]
Hi, did some manage to make it work? 

We want to share the /api route between JWT and Oauth2 at the moment it doesn't work without this guard controller for oauth2

**Comment by yceruto** [comment]
Hi, I created a gist https://gist.github.com/yceruto/f1500b350065481568a3b2971fde8d0f of what I've achieved so far.

I made it work for most of grant, however it's not compatible with Client credentials grant (https://oauth2.thephpleague.com/authorization-server/client-credentials-grant/) because how Guard authenticator works. The problem is this method:
```php
public function getUser($userIdentifier, UserProviderInterface $userProvider): ?UserInterface;
```
Returning `null` here, (that mean no user and it's the case for Client credentials grant), the guard authenticator flow will throw a `UsernameNotFoundException`. I'm no sure there is a workaround though.

**Comment by yceruto** [comment]
Also you'll have to change the header authorization prefix for JWT to make it work together with OAuth2, because under the same entry point both authenticators cannot use `Bearer` at the same time:
```yaml
lexik_jwt_authentication:
    token_extractors:
        authorization_header:
            # needed to avoid authorization header collision with OAuth2 Bearer schema
            prefix: Token
```

**Comment by ajgarlag** [comment]
> Returning `null` here, (that mean no user and it's the case for Client credentials grant), the guard authenticator provider will throw a `UsernameNotFoundException`. I'm no sure there is a workaround though.

Maybe you can represent this scenario with a new `NullUser` class that implements `UserInterface`. 
Then in `createAuthenticatedToken` you can detect if the received `$user` is an instance of `NullUser`, and pass `null` as `$user` to the `OAuth2TokenFactory` as the `OAuth2Provider` does.

**Comment by yceruto** [comment]
@ajgarlag Great idea! I'll try that on my side, thanks!

**Comment by ajgarlag** [comment]
@yceruto I'd like to use your code to submit a PR adding the Guard authenticator. It's OK, or do you prefer to submit it yourself.

**Comment by yceruto** [comment]
@ajgarlag please, go ahead!

I'd like to review your PR, so ping me, thanks!

**Comment by X-Coder264** [comment]
Thank you guys for the effort here. I had also started to work on this a couple of months ago and I saw that the guard requires an user interface which wouldn't work with the client credentials grant at which point I stopped working on it as I haven't had the time to research how we could work around that. I like the `NullUser` idea :+1:
