### ISSUE TITLE
Authorization code request always denied

### ISSUE THREAD

**Issue by RichardWeug** [trikoder/oauth2-bundle#152]
I'm creating a client using the following command:
`php bin/console trikoder:oauth2:create-client --redirect-uri=https://test.com --grant-type=authorization_code`

I use the credentials to request a token:
`https://localhost:8000/authorize?client_id=acd7e11a1f9665bd1ea614ab7c194963&response_type=code&state=5ca75bd30&redirect_uri=https%3A%2F%2Ftest.com`

However, I always get the same response:
`error=access_denied&error_description=The+resource+owner+or+authorization+server+denied+the+request.&hint=The+user+denied+the+request&message=The+resource+owner+or+authorization+server+denied+the+request.`

**Comment by coderiekelt** [comment]
How did you fix?

**Comment by Tetragramat** [comment]
There is missing documentation. You need to approve authorization in event `trikoder.oauth2.authorization_request_resolve`
see https://github.com/trikoder/oauth2-bundle/blob/v3.x/Controller/AuthorizationController.php#L78
