### ISSUE TITLE
Missing public client support without workaround

### ISSUE THREAD

**Issue by mtnalonso** [trikoder/oauth2-bundle#156]
When making an Access Token request with an access code, it is always required to send the `client_secret` in the request if this exists on the database, as all clients have a secret and are treated as confidential.

This is related to how the [phpleague](https://github.com/thephpleague/oauth2-server) library validates the Access Token request up to version **7.4**. It appears that it determines if a given client is public or confidential based on the existence of the client secret on the database.

Once an Access Token Request comes in, the function `respondToAccessTokenRequest()` in [src/Grant/AuthCodeGrant.php](https://github.com/thephpleague/oauth2-server/blob/7.4.0/src/Grant/AuthCodeGrant.php) its invoked. At the first line of the function, it calls `validateClient()` from [src/Grant/AbstractGrant.php](https://github.com/thephpleague/oauth2-server/blob/7.4.0/src/Grant/AbstractGrant.php) which tries to get the `Client` entity based on the client id, the grant type and the client secret. This client secret is null if not provided on the request body parameters.
Thus, when validating the client, the server finds that the password of the client is not null, invalidating the request. Otherwise, if the client secret generated on the database is provided on the Access Token request, the server does find the client, validating the request.

It seems that the validation mechanism is improved on version **8.0.0** of [oauth2-server](https://github.com/thephpleague/oauth2-server), having now a field on the client that determines if it `isConfidential()` or not ([src/Entities/ClientEntityInterface.php](https://github.com/thephpleague/oauth2-server/blob/8.0.0/src/Entities/ClientEntityInterface.php))

The problem that I found is that I was not able to specify or create a public client on the bundle unless, after creating a client with the command, the client secret is deleted manually from the database.

I also checked https://github.com/trikoder/oauth2-bundle/pull/140 that I understood after identifying this issue but it is still open. Is there any estimated release date for a new release that includes that PR and also uses the new version of the server?

Thank you in advance!

**Comment by X-Coder264** [comment]
@mtnalonso Thanks for the feedback. Our focus atm is adding [Symfony 5 support](https://github.com/trikoder/oauth2-bundle/pull/150) to master and then we will focus on getting #140 merged.

**Comment by X-Coder264** [comment]
@mtnalonso https://github.com/trikoder/oauth2-bundle/pull/167 just got merged. We will tag 3.0 which will contain this soon.
