### ISSUE TITLE
Add config option that allows us to override role name prefix

### ISSUE THREAD

**Issue by miroslav-marinkovic** [trikoder/oauth2-bundle#16]
Currently, role names are prefixed with `ROLE_OAUTH2_`. A config option to override this would make bundle a lot more flexible.

**Comment by rjwebdev** [comment]
Should this role name be configured in the firewall or in the bundle configuration?

**Comment by spideyfusion** [comment]
@rjwebdev Definitely in the bundle configuration.

**Comment by HypeMC** [comment]
Closed with #94.
