### ISSUE TITLE
New release with sf5 supports

### ISSUE THREAD

**Issue by metfan** [trikoder/oauth2-bundle#176]
Hello, 

I don't know your release lifecycle. Do you plan to release soon a new tag including symfony 5 support?

Thank you.

**Comment by X-Coder264** [comment]
@metfan Yes, we do. The plan was to release it today but we haven't had the time today for it so 3.0 with Symfony 5 support will be tagged tomorrow.

**Comment by rlweb** [comment]
Would be useful to leave this open until it's been done!

**Comment by X-Coder264** [comment]
@metfan @rlweb 3.0 was just tagged.
