### ISSUE TITLE
Unable to get any response on token api - same 500 error

### ISSUE THREAD

**Issue by rbaarsma** [trikoder/oauth2-bundle#19]
Hi,

Just installed this bundle and trying to get a token. Managed to update the schema and create a client. Everything seems fine and my application still works

When I call the api I always get this error:

```
{"code":500,"message":"Resources are not supported in serialized data. Path: Zend\\Diactoros\\Stream -> Zend\\Diactoros\\Response"}
```

I've tried a bit of debugging in the `TokenController`, but even if I simply return the new Response in the first line, it still gives this error.

Is there some dependency I'm missing or is it not working in php 7.2.12?
I checked composer.lock -- it has installed `zendframework/zend-diactoros` `1.8.6` and `trikoder/oauth2-bundle` `v1.1.0` and `league/oauth2-server` `7.2.0`.

**Comment by rbaarsma** [comment]
I dived into this issue more and eventually figured out that through the combination of the `friendsofsymfony/rest-bundle` and `jms/serializer-bundle` the Response object is being serialized, which fails. The solution was to move the `/token` api out of the `/api` namespace configured in the `fos_rest`.`zone` configuration.

I'll close this issue. Maybe my explanation will help someone else

**Comment by spideyfusion** [comment]
Looking at the exception message, it seems to originate from the [jms/serializer](https://github.com/schmittjoh/serializer) library:

https://github.com/schmittjoh/serializer/blob/master/src/GraphNavigator/SerializationGraphNavigator.php#L158

Are you using [jms/serializer](https://github.com/schmittjoh/serializer) or [jms/serializer-bundle](https://github.com/schmittjoh/JMSSerializerBundle) in your project? Something is automatically trying to serialize the PSR-7 compliant response (which is normally handled by the [PSR-7 bridge](https://symfony.com/doc/current/components/psr7.html) that this bundle relies on).

**Comment by spideyfusion** [comment]
@rbaarsma Unbelievable, we posted a comment at the exact second. :D
