### ISSUE TITLE
unsupported_grant_type

### ISSUE THREAD

**Issue by guillaumederamecourt** [trikoder/oauth2-bundle#200]
I'm trying to test my fresh installation in SF5.

I'm using "charles" to make POST request to `/token`:

`{
 "grant_type=client_crediantials",
"client_id = 8022",
"client_secret = 123",
"scope" = read",
}
`

With the good headers like this : 

`Content-Type` | `application/x-www-form-urlencoded`

And my client here : 

|identifier|secret|scope|redirect uri|grant type|          
| --------|:------|:------|----------|----------| 
|8022|123|read| |client_credential|

And each time, the response is :

`{
	"error": "unsupported_grant_type",
	"error_description": "The authorization grant type is not supported by the authorization server.",
	"hint": "Check that all required parameters have been provided",
	"message": "The authorization grant type is not supported by the authorization server."
}`

I've follow the installation, and everything in my `trikoder_oauth2.yaml`appears to be good.

What am I doing wrong, I have completely followed the installation guide.

**Comment by avieyto** [comment]
Make sure the following:

1. Client must exists in the DB, do you previously created?
2. request content must be grant_type=client_credentials&client_id=8022&client_secret=123&scope=read, since the content-type is application/x-www-form-urlencoded you must pass content as a query params.
3. Be sure is client_credentials, ending in s

**Comment by guillaumederamecourt** [comment]
Thanks for the answer.

In fact i realize, that my charles application does an application/json call and not application/x-www-form-urlencoded

Thanks a lot.

I can close the issue

**Comment by guillaumederamecourt** [comment]
Hello again,

I'm trying now the same things with the grant_type=password.

My actual client 

|identifier|secret|scope|redirect uri|grant type|          
| --------|:------|:------|----------|----------| 
|8022|123|read| |password, client_credentials, authorization_code|

And i'm make a call to /token


`{
	"error": "invalid_grant",
	"error_description": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.",
	"hint": "",
	"message": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
}`

What's wrong ?
