### ISSUE TITLE
Access Denied /authorize

### ISSUE THREAD

**Issue by guillaumederamecourt** [trikoder/oauth2-bundle#207]
Hi,

I'm trying to request /authorize and each time i've the `access_denied` message.

And i'm pretty sure to follow the guide :(

My client have the gran type : authorization_code

And i'm requesting : /authorize?client_id=8022&redirect_uri=my_uri&response_type=code&scope=read

What's wrong ?

Thanks

**Comment by WithAlex** [comment]
see : https://github.com/trikoder/oauth2-bundle/pull/177/files

**Comment by X-Coder264** [comment]
Closing pending inactivity. The documentation for the authorization code grant is on the link above (and hopefully it will be merged soon).
