### ISSUE TITLE
Store a client's name

### ISSUE THREAD

**Issue by frostieDE** [trikoder/oauth2-bundle#209]
I was wondering why this bundle does not store the name of an OAuth client. 

Currently, the client entity does not have a property `name`. Interestingly, the original client entity in league/oauth2-server seems to require a name because all classes implementing `ClientEntityInterface` require a method `getName()`. As of now, this library returns the [client identifier instead of a name](https://github.com/trikoder/oauth2-bundle/blob/v3.x/League/Entity/Client.php#L26).

I suppose implementing a name property would be a BC break?!

**Comment by X-Coder264** [comment]
We didn't have the need for a `name` field in our projects since the `identifier` is a string already (which can be filled with whatever you need as long as it's unique) so we've been using it as a "name".

> I suppose implementing a name property would be a BC break?!

Yes, that would be a BC break.

**Comment by frostieDE** [comment]
Sure, but the the name would appear in urls like the authorize endpoint which seems ugly 😄 

But I just found #145 which seems to be a proper solution for my problem :-)
