### ISSUE TITLE
About cascade of oauth2_authorization_code table

### ISSUE THREAD

**Issue by okazy** [trikoder/oauth2-bundle#210]
If there are any related records in oauth2_authorization_code table, the client cannot be deleted by `trikoder:oauth2:delete-client` command.
Why isn't cascade set in oauth2_authorization_code table?
I think it is better to set CASCADE or SET NULL like the oauth2_access_token or oauth2_refresh_token table.

```diff
        <many-to-one field="client" target-entity="Trikoder\Bundle\OAuth2Bundle\Model\Client">
-            <join-column name="client" referenced-column-name="identifier" nullable="false" />
+            <join-column name="client" referenced-column-name="identifier" nullable="false" on-delete="CASCADE" />
        </many-to-one>
```

**Comment by yceruto** [comment]
Done in https://github.com/trikoder/oauth2-bundle/pull/216

**Comment by X-Coder264** [comment]
Yep, thx @yceruto. I'm closing the issue as the PR with the fix has been merged.
