### ISSUE TITLE
Custom Claims

### ISSUE THREAD

**Issue by mrtnzagustin** [trikoder/oauth2-bundle#213]
First of all, thanks for this amazing bundle.

Is there a way to include custom claims ? There is a [PR](https://github.com/thephpleague/oauth2-server/issues/1120) in thephpleague/oauth2-server for this but i want to know if there is a workaround in this bundle. 

Regards,
Agustin

**Comment by X-Coder264** [comment]
@mrtnzagustin No, currently there isn't. If/when such a thing gets merged in the thephpleague/oauth2-server we'll be more than happy to support it in the bundle.
