### ISSUE TITLE
A Token was not found in the TokenStorage.

### ISSUE THREAD

**Issue by shoaib-akhunzada** [trikoder/oauth2-bundle#22]
Hi,

i have installed this bundle and trying to get a token. As token generated fine but whenever i call Api with that token in header, this give me blank screen with with a status 401. Is this some kind of my configuration issue or compatibility. 
i use postman for api call.
PHP : 7.2
Symfony : 4.2
Ubantu : 14.4

regards
shoaib

**Comment by shoaib-akhunzada** [comment]
The issue resolved, this issue was because of some permission to public and private keys.
-- chmod -R g+rx ...
thanks

**Comment by spideyfusion** [comment]
@shoaib-akhunzada Maybe it would be a good idea to add a note about key permissions in the documentation. What are your thoughts?

**Comment by spideyfusion** [comment]
@shoaib-akhunzada Thanks for sharing!
