### ISSUE TITLE
Is there any reason why the property 'secret' in Client class is private?

### ISSUE THREAD

**Issue by ramil8090** [trikoder/oauth2-bundle#225]
Hello,

would you explain to me why the property 'secret' in Model\Client class is private?

**Comment by X-Coder264** [comment]
You have the `getSecret` getter method for it? What's the problem exactly?

**Comment by ramil8090** [comment]
I want to modify only 'secret' in existing Client, but there is not setter for this property.

**Comment by yceruto** [comment]
I needed this as well for a "reset client secret" action without re-create the whole Client entity and its associations.

**Comment by yceruto** [comment]
However, the property is fine as private, just adding a setter would help.

**Comment by ramil8090** [comment]
But it is impossible to add a setter in child class for private property of parent class. Can you change this property from private to protected?

**Comment by yceruto** [comment]
@ramil8090 I was indeed refering to add the setter here rather than make it protected :)

**Comment by ramil8090** [comment]
Let ask the last question please. Who will add a setter to the 'secret' property? Maybe you or i should make the pull request?

**Comment by yceruto** [comment]
I'd wait for @X-Coder264 answer, maybe he has a reasonable cause of why the setter doesn't exist from day one.

**Comment by X-Coder264** [comment]
Now that I look at it I don't see why we don't have a setter for it nor can I remember a reason why we didn't put the setter there in the first place. So a PR to add that would be highly appreciated, if nobody sends it I'll probably send it myself this weekend when I'll have some free time.
