### ISSUE TITLE
Unrecognized option "grant_types" under "trikoder_oauth2.authorization_server"

### ISSUE THREAD

**Issue by maximw** [trikoder/oauth2-bundle#233]
Hi!
I'm using version  **"trikoder/oauth2-bundle": "^3.1"**
I installed Bundle by command "`composer require trikoder/oauth2-bundle`", and then it was configured be Symfony Flex.
If copypasted config from `README.md` to `config/packages/trikoder_oauth2.yaml`. But then got error:

`Unrecognized option "grant_types" under "trikoder_oauth2.authorization_server". Available options are "access_token_ttl", "auth_code_ttl", "enable_auth_code_grant", "enable_client_credentials_grant", "enable_implicit_grant", "enable_password_grant", "enable_refresh_token_grant", "encryption_key", "encryption_key_type", "private_key", "private_key_passphrase", "refresh_token_ttl", "require_code_challenge_for_public_clients".`

**Comment by X-Coder264** [comment]
Sorry for the confusion. The readme on the 3.x branch reflects the state of the upcoming 3.2 release which is due soon.

Currently the latest tag (3.1.1) does not have the `grant_types` key. For the current configuration example check the 3.1.1 readme: https://github.com/trikoder/oauth2-bundle/blob/v3.1.1/README.md

**Comment by maximw** [comment]
Thanks!
