### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by froozeify** [trikoder/oauth2-bundle#247]
Hi, I was working on my future pull request for event.

When I get on my fork and also [here](https://github.com/trikoder/oauth2-bundle/actions/runs/389661691), the tests are now marked on failed. 

I don't know why it's failed, any ideas why ?

**Comment by X-Coder264** [comment]
```
The "https://getcomposer.org/download/1.9.3/composer.phar" file could not be downloaded: SSL: Connection reset by peer
failed to open stream: HTTP request failed!
Retrying...
The "https://getcomposer.org/download/1.9.3/composer.phar" file could not be downloaded: SSL: Connection reset by peer
failed to open stream: HTTP request failed!
Retrying...
Failed to decode zlib stream
Service 'php' failed to build : The command '/bin/sh -c curl --show-error https://getcomposer.org/installer | php --         --install-dir=/app/bin         --filename=composer         --version=${COMPOSER_VERSION}' returned a non-zero code: 1
Error: Process completed with exit code 1.
```

It looks like a networking issue, hopefully it's gonna be resolved soon.

**Comment by froozeify** [comment]
Ok, great. Don't know how you found that error message but 👍 

Maybe we should try with [composer 2](https://blog.packagist.com/composer-2-0-is-now-available/), if i remember correctly, the plan to deprecate prettty fast composer 1
