### ISSUE TITLE
Need help with Authorization Code Grant

### ISSUE THREAD

**Issue by PaulCombal** [trikoder/oauth2-bundle#27]
Hello,
I just started doing a few tests with your package, and it looks well built and polished!
I encountered an issue I did not manage to solve though: I cannot get the authorization to work because of an `unsupported_grant_type` error. The Authorization Code Grant should be feature since I read

> API endpoint for client authorization and token issuing

on the repo's README.

I set up the bundle as stated in the readme, everything seems to work as intended. 

However, when I do the following request:

`GET http://api.mydomain.local/oauth/token?response_type=code&client_id=foo&state=5ca75bd30&scope=ifttt&redirect_uri=http://google.com`

I get the error: 
```
{
    "error": "unsupported_grant_type",
    "message": "The authorization grant type is not supported by the authorization server.",
    "hint": "Check that all required parameters have been provided"
}
```
I mean, I don't get why I'm getting this error when I specified response_type=code and client_id=xxx..

Did I miss something?

Thank you

**Comment by spideyfusion** [comment]
Hi @PaulCombal 

We still don't have support for the `authorization_code` grant type, but we're working on getting it done in this merge request: https://github.com/trikoder/oauth2-bundle/pull/18

**Comment by spideyfusion** [comment]
The `authorization_code ` grant type is now available on the `master` branch. Feel free to open another issue if you need any help with the implementation.
