### ISSUE TITLE
Symfony 5.3 new user interface support

### ISSUE THREAD

**Issue by vuryss** [trikoder/oauth2-bundle#278]
Symfony 5.3 introduces changes in UserInterface. `getUsername` method is no longer required by the interface and instead a new `getUserIdentifier` is used.

https://symfony.com/blog/new-in-symfony-5-3-improvements-for-security-users

This causes issues with the UserConverter as it depends on the old method.

**Comment by HypeMC** [comment]
@vuryss Could you please check if this was fixed with https://github.com/symfony/symfony/pull/41493 ?

**Comment by vuryss** [comment]
@HypeMC it appears so, yeah.
