### ISSUE TITLE
How to get access token for all types of grants?

### ISSUE THREAD

**Issue by rl-Rahul** [trikoder/oauth2-bundle#282]
I am currently integrating [Trikoder Bundle](https://github.com/trikoder/oauth2-bundle) in Symfony 5.3 API based project. But I ran into an issue while using the bundle. Earlier when we `fos_oauth` bundle, we will get the access token from `grantAccesToken()` function. But when I came to use this bundle I think it is bit hard to use it and its functionalities. Somehow I am able to solve some of my problems and got a `200 OK` response. But the problem still I am facing now is that I am not getting any access tokens. 
![NoToken](https://user-images.githubusercontent.com/60173473/121872071-79254580-cd22-11eb-9ef6-17139a9c590d.png)
Please find the image attached.
Also please guide me to implement password `--grant-type=password` in my project. I am developing an API based application which have social login too..

**Comment by X-Coder264** [comment]
I'm not sure what your issue is. The screenshot that you've posted does not mean anything to me unfortunately. Also you shouldn't really be using the password grant for a new project. The password grant has been deprecated by the OAuth specification and will be completely removed in a future version. You should use authorization code grant with PKCE instead.

https://oauth2.thephpleague.com/authorization-server/which-grant/

As far as access token requests go here are the tests for various grants:

https://github.com/trikoder/oauth2-bundle/blob/v3.x/Tests/Acceptance/TokenEndpointTest.php

**Comment by rl-Rahul** [comment]
> I am currently integrating [Trikoder Bundle](https://github.com/trikoder/oauth2-bundle) in Symfony 5.3 API based project. But I ran into an issue while using the bundle. Earlier when we `fos_oauth` bundle, we will get the access token from `grantAccesToken()` function. But when I came to use this bundle I think it is bit hard to use it and its functionalities. Somehow I am able to solve some of my problems and got a `200 OK` response. But the problem still I am facing now is that I am not getting any access tokens.
> ![NoToken](https://user-images.githubusercontent.com/60173473/121872071-79254580-cd22-11eb-9ef6-17139a9c590d.png)
> Please find the image attached.
> Also please guide me to implement password `--grant-type=password` in my project. I am developing an API based application which have social login too..

Sorry for the misunderstanding!! I am actually expecting a response like 
![YesToken](https://user-images.githubusercontent.com/60173473/121876162-dd4a0880-cd26-11eb-9c82-bd3f15eec9e1.png)
Unfortunately I am not able to build this kind of response. I am new with `TrikoderBundle`.

**Comment by X-Coder264** [comment]
The auth code grant works like this:

1. Your frontend and/or mobile app makes a request to the authorize endpoint with all needed query parameters -> https://github.com/trikoder/oauth2-bundle/blob/v3.x/Tests/Acceptance/AuthorizationEndpointTest.php#L87
2. If the user is not logged in you redirect them to your login page (which can contain the standard username/password form and/or the social login buttons) - you need to create the  `AuthorizationCodeListener` (an example implementation is shown in the documentation linked below)
3. After the user successfully logs in you must redirect them back to the previous authorize URL. That request will now be approved as the user is logged in and the user will now be redirected back to the redirect URI which was specified in the authorize URL as a query parameter (plus the redirect response will now have the `code` query parameter)
4. Your frontend and/or mobile app reads that `code`query param and sends it to the token endpoint to exchange it for the access token -> https://github.com/trikoder/oauth2-bundle/blob/v3.x/Tests/Acceptance/TokenEndpointTest.php#L160

Here's the auth code grant documentation for the bundle -> https://github.com/trikoder/oauth2-bundle/blob/854faf9474dded26b69473237143d5ef7a333102/docs/authorization-code-grant.md

For a more detailed explanation of the auth code grant see here: https://auth0.com/blog/oauth-2-best-practices-for-native-apps/

    1. Client app opens a browser tab with the authorization request.
    2. Authorization endpoint receives the authorization request, authenticates the user, and obtains authorization. Authenticating the user may involve chaining to other authentication systems.
    3. Authorization server issues an authorization code to the redirect URI.
    4. Client receives the authorization code from the redirect URI.
    5. Client app presents the authorization code at the token endpoint.
    6. Token endpoint validates the authorization code and issues the tokens requested.
