### ISSUE TITLE
can't get commands

### ISSUE THREAD

**Issue by msechi** [trikoder/oauth2-bundle#29]
Hi guys
I can't get the commands you released 1 week ago, maybe you need to make a new release (1.1.1)?

thanks
M

**Comment by spideyfusion** [comment]
We're in the process of creating additional console commands for deleting and listing clients. Once those are complete we'll tag a new release.

**Comment by X-Coder264** [comment]
v2.0.0-beta1 was tagged and it contains all those commands so I consider this issue as being fixed.
