### ISSUE TITLE
How can I get data from access token?

### ISSUE THREAD

**Issue by gaisindanil** [trikoder/oauth2-bundle#290]
Hi everyone, How can I get data from access token? Is there any decoder for this bundle?

**Comment by Jwilsonps** [comment]
You can view the content of the access_token via a web tool; https://jwt.io/

Programatically you could use something like https://packagist.org/packages/firebase/php-jwt

**Comment by X-Coder264** [comment]
@gaisindanil What's your exact use-case?

The League OAuth2 server uses https://github.com/lcobucci/jwt for creating the JWT token so I recommend that package if you need to read them.
