### ISSUE TITLE
sensio/framework-extra-bundle dependencya problem with 3.2.0

### ISSUE THREAD

**Issue by sdespont** [trikoder/oauth2-bundle#305]
This commit https://github.com/trikoder/oauth2-bundle/commit/286cab0903029d17898cc617ae88d26f808c3a9e (committed on 5 Feb 2021 ) remove the dependency of sensio/framework-extra-bundle but has never been released.

Would it be possible to have a new release to avoid conflict in composer due to this dependency please?

**Comment by X-Coder264** [comment]
The new release has been tagged. Anybody still using this package should migrate over to https://github.com/thephpleague/oauth2-server-bundle though.
