### ISSUE TITLE
Should the enabled grant types be configurable?

### ISSUE THREAD

**Issue by cGuille** [trikoder/oauth2-bundle#34]
Hello,

I am currently in the process of deciding to use this bundle or directly the underlying library from the PHP league.

The issues that I have are:
- I would need to configure which grant types are enabled. I do not think it is possible a the moment since [they are enabled in the bundle extension](https://github.com/trikoder/oauth2-bundle/blob/f16ec67f2fa8dbf8fedd78488d625cef2db5b90d/DependencyInjection/TrikoderOAuth2Extension.php#L77-L90).
- I would need to override the password grant type with a custom one since the provided password grant is not flexible enough for us: we would need more than username and password in order to authenticate users. At the moment, the only way I can imagine to do that is to override the service `league.oauth2.server.grant.password_grant` and hope it still works when the bundle gets updated.

1. Do you think that it would be a good idea to make the enabled grant types configurable?
2. Would you consider a pull request about this?

Kind regards,

Guillaume.

**Comment by HypeMC** [comment]
@cGuille Hi, thank you for considering using our oauth bundle. Sorry it took us a while to get to your question. Making the grant types configurable sounds like a great idea and an PR would be greatly appreciated if your still up for it.
