### ISSUE TITLE
Client Model should not use Objects for Grants / Scopes / Request Uris

### ISSUE THREAD

**Issue by beutelsend** [trikoder/oauth2-bundle#35]
Hey,

the usage of Objects for Grants / Scopes / Request Uris in the Model for Clients causes me headaches at the moment. In context of the bundle, everything is fine. However, the bundle relies upon the magic conversion of said objects with __toString() by doctrine, which can not be relied upon. The Model should only use primitives or other Models. 

Concretely, i am running into a lot of trouble when using your model in conjunction with API Platform, which relies on Symfonys Serializers. 

Thanks for your hard work on this project, this is so far one of the only issues i ran into.

Greetings,

B

**Comment by beutelsend** [comment]
Small Example, when saving, i get this:

```
Expected argument of type "Trikoder\Bundle\OAuth2Bundle\Model\RedirectUri", "array" given at property path "redirectUris".
```

This is due to the fact that Symfonys property-acessor component does not support parameter unpacking and it will try to just set an array of strings / objects on the setRequestUri Accessor, instead of trying to use ...$value.

I think this issue is in the bundle, not in Symfony itself.

**Comment by vstanchev** [comment]
I'd like to bump this up by saying that we have the same issue when creating a Sonata Admin page for managing OAuth2 clients.

**Comment by spideyfusion** [comment]
@vstanchev Could you please provide some code examples to help illustrate the issue you're having with your custom implementation?

**Comment by pdesgarets** [comment]
Same use case as @vstanchev here.
Not having the entities written as "standard" Symfony entities is a real pain to get forms working and manage client entities with something else than the Commands provided with this bundle (like a "standard" SF entity = having setters and getters for every field, return nullable typed values, having a constructor that can run without arguments, if the field is an array there should be either an "addAttribute" method or/and a "setAttribute" method that accepts arrays...).

**Comment by spideyfusion** [comment]
I'm going to close this issue due to inactivity. Please provide us with concrete code examples and use cases if you'd like us to investigate it further.
