### ISSUE TITLE
There are no commands defined in the "trikoder:oauth2" namespace.

### ISSUE THREAD

**Issue by unlikenesses** [trikoder/oauth2-bundle#39]
Using Symfony 4, after following the [installation instructions](https://github.com/trikoder/oauth2-bundle#installation) and starting the [basic setup instructions](https://github.com/trikoder/oauth2-bundle/blob/master/docs/basic-setup.md), I run `php bin/console trikoder:oauth2:create-client` and get this error:

> There are no commands defined in the "trikoder:oauth2" namespace.

**Comment by ajgarlag** [comment]
These commands are available in master branch only. If you are using the stable `v1.1.0` version, you should create clients using SQL statements: https://github.com/trikoder/oauth2-bundle/blob/v1.1.0/docs/basic-setup.md

**Comment by unlikenesses** [comment]
Thanks!
