### ISSUE TITLE
Error in token controller

### ISSUE THREAD

**Issue by asalisaf** [trikoder/oauth2-bundle#42]
Hey
I got this error on calling token route:

```Cannot autowire argument $serverRequest of "trikoder.oauth2.controller.token_controller:indexAction()": it references interface "Psr\Http\Message\ServerRequestInterface" but no such service exists. Did you create a class that implements this interface?```

**Comment by rsuper** [comment]
I had this too. I fixed it by creating these services:
```
    Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory: ~

    Psr\Http\Message\ServerRequestInterface:
        factory: 'Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory:createRequest'
        arguments: ['@=service("request_stack").getMasterRequest()']
```

**Comment by unlikenesses** [comment]
I am also getting this error. Perhaps it's due to a recent update in Symfony, because it was working a week ago.

**Comment by spideyfusion** [comment]
We are working on this in https://github.com/trikoder/oauth2-bundle/pull/43. The plan is to have it merged by tomorrow.

**Comment by unlikenesses** [comment]
Can confirm that it now works without needing to add the services in [this answer](https://github.com/trikoder/oauth2-bundle/issues/42#issuecomment-484908039).

**Comment by rubenodeman** [comment]
After the update from today I'm getting this error: 

The service alias "Psr\Http\Message\ServerRequestFactoryInterface" does not exist.

**Comment by spideyfusion** [comment]
@rubenodeman `SensioFrameworkExtraBundle` should [setup](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/Resources/config/psr7.xml#L28) the default autowiring aliases for you. Have you tried clearing your entire `var/cache` folder?

If you're still getting the error, post the entire stack trace of the error please.

**Comment by rubenodeman** [comment]
Thanks for the quikc reply! Still getting the error after clearing the cache.

(1/1) InvalidArgumentExceptionThe service alias "Psr\Http\Message\ServerRequestFactoryInterface" does not exist.
--
in ContainerBuilder.php line 899
at ContainerBuilder->getAlias('Psr\\Http\\Message\\ServerRequestFactoryInterface')in TrikoderOAuth2Extension.php line 90
at TrikoderOAuth2Extension->assertPsrHttpAliasesExist(object(ContainerBuilder))in TrikoderOAuth2Extension.php line 75
at TrikoderOAuth2Extension->process(object(ContainerBuilder))in ExtensionCompilerPass.php line 34
at ExtensionCompilerPass->process(object(ContainerBuilder))in Compiler.php line 95
at Compiler->compile(object(ContainerBuilder))in ContainerBuilder.php line 750
at ContainerBuilder->compile()in Kernel.php line 544
at Kernel->initializeContainer()in Kernel.php line 133
at Kernel->boot()in Kernel.php line 193
at Kernel->handle(object(Request))in index.php line 25

**Comment by spideyfusion** [comment]
@rubenodeman Make sure you have the `SensioFrameworkExtraBundle` enabled in your kernel:

```php
Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true]
```

**Comment by rubenodeman** [comment]
Solved! Thanks for the support!

**Comment by spideyfusion** [comment]
@rubenodeman No problem. I'll add a check in a compiler pass to alert the developer if the required bundles are not enabled so other folks don't run into the same situation. :)

**Comment by rbaarsma** [comment]
I have this issue after upgrading from sensio/framework-bundle 5.2.4 to 5.3.1. I've tried clearing the cache manually (`rm -rf var/cache`) and have checked that sensioFrameworkExtraBundle is indeed enabled.

**Comment by rbaarsma** [comment]
Opened an issue on sensio/framework-extra-bundle: https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/620

**Comment by rbaarsma** [comment]
I just tried to update trikoder/oauth2-bundle to the `dev-master` version (with the sensio/framework-extra-bundle at 5.3.1), but that doesn't want to install

```
  Problem 1
    - Can only install one of: symfony/psr-http-message-bridge[v1.2.0, v1.0.2].
    - Can only install one of: symfony/psr-http-message-bridge[v1.2.0, v1.0.2].
    - Can only install one of: symfony/psr-http-message-bridge[v1.2.0, v1.0.2].
    - trikoder/oauth2-bundle dev-master requires symfony/psr-http-message-bridge ^1.2 -> satisfiable by symfony/psr-http-message-bridge[v1.2.0].
    - Installation request for trikoder/oauth2-bundle dev-master -> satisfiable by trikoder/oauth2-bundle[dev-master].
    - Installation request for symfony/psr-http-message-bridge (locked at v1.0.2) -> satisfiable by symfony/psr-http-message-bridge[v1.0.2].
```

Note: I'm using symfony 4.2 (not 4.3).. 
And I don't have nyholm/psr7 installed, as it isn't a requirement for anything as far as I can tell.. they even removed it as a requirement in sensio/framework-extra-bundle 5.3.0

**Comment by spideyfusion** [comment]
@rbaarsma What version of `symfony/psr-http-message-bridge` are you targeting in your `composer.json`. It should be at least `1.2`.

**Comment by rbaarsma** [comment]
Not targeting any version. Shouldn't that requirement be automatically upgraded when  your requirements are to have it at ^1.2. It's not like I'm limiting that version somehow?

**Comment by X-Coder264** [comment]
@rbaarsma Try `composer update trikoder/oauth2-bundle --with-dependencies`.

**Comment by rbaarsma** [comment]
Okay so eventually I did the following:

```
bash$ composer require nyholm/psr7
# changed composer.json manually to use "dev-master " as a value for trikoder/oauth2-bundle and "^1.2" for "symfony/psr-http-message-bridge"
bash$ composer update trikoder/oauth2-bundle symfony/psr-http-message-bridge
```

Note that it didn't work to just update trikoder-oauth2-bundle to dev-master.

This fixes my issue. I hope this version gets tagged soon ;)

**Comment by X-Coder264** [comment]
Of course just updating `trikoder-oauth2-bundle` to `dev-master ` didn't fix the issue. It was documented in #43 that `nyholm/psr7` should be manually required too.

I'm glad that we finally fixed the issue.

**Comment by X-Coder264** [comment]
v2.0.0-beta1 was tagged and 2.0 will be tagged soon too so I'm closing this issue.
