### ISSUE TITLE
Attempted to load class "Psr17Factory" from namespace "Nyholm\Psr7\Factory".

### ISSUE THREAD

**Issue by unlikenesses** [trikoder/oauth2-bundle#45]
Symfony 4. I recently encountered [this problem](https://github.com/trikoder/oauth2-bundle/issues/42), and solved it with [this solution](https://github.com/trikoder/oauth2-bundle/issues/42#issuecomment-484908039). This means I have been able to request a token successfully. When I now use it to call an endpoint, I receive this error:

> Attempted to load class "Psr17Factory" from namespace "Nyholm\Psr7\Factory".

Stack trace:

> in var/cache/dev/ContainerOERATu7/getSecurity_Authentication_Listener_Oauth2_ApiService.php (line 9)

```php
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.listener.oauth2. api' shared service.

$a = new \Nyholm\Psr7\Factory\Psr17Factory();

return $this->privates['security.authentication.listener.oauth2. api'] = new \Trikoder\Bundle\OAuth2Bundle\Security\Firewall\OAuth2Listener(($this->services['security.token_storage'] ?? ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage())), ($this->privates['security.authentication.manager'] ?? $this->getSecurity_Authentication_ManagerService()), new \Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory($a, $a, $a, $a));
```

**Comment by spideyfusion** [comment]
Symfony recently did a breaking change in the latest version of [sensio/framework-extra-bundle](https://github.com/sensiolabs/SensioFrameworkExtraBundle/commit/4544cab113509a1988481ecd7e1b235be087f626). We are working on making a change on the bundle level so we don't force people to use a specific PSR-7/17 implementation. You can track the progress [here](https://github.com/trikoder/oauth2-bundle/pull/43/).

Could you please try checking out to the `psr-bridge-upgrade` branch and verify everything works for you?

Don't forget to install [nyholm/psr7](https://github.com/Nyholm/psr7) as well:

```sh
composer require nyholm/psr7
```

**Comment by unlikenesses** [comment]
It works now -- thanks!

**Comment by Crisme24** [comment]
Thanks it is works for me as well!!!

**Comment by fardus** [comment]
Thanks it's works

**Comment by nikserg** [comment]
@spideyfusion solution works for me:

`composer require nyholm/psr7`
