### ISSUE TITLE
 ScopeManager missing for Doctrine

### ISSUE THREAD

**Issue by rsuper** [trikoder/oauth2-bundle#46]
I'm getting an error when using scopes. When supplying any scope in my request, I get an `invalid_scope` error, even though it is defined for the client.

I think this is because the `ScopeManager` is missing for Doctrine. It [uses the InMemory variant](https://github.com/trikoder/oauth2-bundle/blob/v1.1.0/Resources/config/storage/doctrine.xml#L21) of the manager. The Doctrine variant does not exist at all.

**Comment by spideyfusion** [comment]
Did you register the scope in the bundle configuration?

```
# Scopes that you wish to utilize in your application.
# This should be a simple array of strings.
scopes:
    - scope_a
    - scope_b
```

**Comment by rsuper** [comment]
Ah yes, I totally missed that line. It's working now, thanks!
