### ISSUE TITLE
Deprecation warning in Doctrine2 Dbal Types

### ISSUE THREAD

**Issue by gonzaloplaza** [trikoder/oauth2-bundle#50]
After latest Doctrine2 update, we're getting this deprecation warnings.

`Deprecated: The type "oauth2_redirect_uri" was implicitly marked as commented due to the configuration. This is deprecated and will be removed in DoctrineBundle 2.0. Either set the "commented" attribute in the configuration to "false" or mark the type as commented in "Trikoder\Bundle\OAuth2Bundle\DBAL\Type\RedirectUri::requiresSQLCommentHint()."`

`Deprecated: The type "oauth2_scope" was implicitly marked as commented due to the configuration. This is deprecated and will be removed in DoctrineBundle 2.0. Either set the "commented" attribute in the configuration to "false" or mark the type as commented in "Trikoder\Bundle\OAuth2Bundle\DBAL\Type\Scope::requiresSQLCommentHint()`

Edit: Looks like it's happening with all bundle entities

**Comment by X-Coder264** [comment]
This deprecation came with DoctrineBundle 1.11 which was released 9 days ago (https://github.com/doctrine/DoctrineBundle/pull/947).

A PR fixing this deprecation would be greatly appreciated. I'll try making one before the end of the month if someone doesn't create one sooner.

**Comment by spideyfusion** [comment]
We are going to address this fairly soon in https://github.com/trikoder/oauth2-bundle/pull/60.
