### ISSUE TITLE
Invalid options in docs for authorization_server

### ISSUE THREAD

**Issue by AzeemMichael** [trikoder/oauth2-bundle#67]
Get following error when I run `./bin/console doctrine:schema:update --force`

```Unrecognized options "private_key_passphrase, encryption_key_type, enable_client_credentials_grant, enable_password_grant, enable_refresh_token_grant, auth_code_ttl" under "trikoder_oauth2.authorization_server". Available options are "access_token_ttl", "encryption_key", "private_key", "refresh_token_ttl"```

**Comment by X-Coder264** [comment]
@AzeemMichael Sorry, these "unrecognized" options indeed do not exist on the 1.1.0 release as they were added to the `master` branch after that release was tagged and they will be in the upcoming 2.0 release. In order to fix that error just delete these options from your .yml file.

**Comment by spideyfusion** [comment]
This is now resolved as version 2.0 of the bundle has been released. We also introduced a new branching system in order to exclude future breaking changes from reaching end-users by accident.
