### ISSUE TITLE
Add strict scope mode and scope inheritance in non strict mode

### ISSUE THREAD

**Issue by klja** [trikoder/oauth2-bundle#7]
Requested token should be validated against scopes defined on client.
If no scopes are requested they should be inherited from client scopes.

Proposed behavior for each use case:

| Storage | Client | Request | Token               |
|---------|--------|---------|---------------------|
| A, B, C | A      |         | A / Invalid scope   |
| A, B, C | A      | A       | A                   |
| A, B, C | A      | B       | Invalid scope       |
| A, B, C | A      | F       | Invalid scope       |
| A, B, C | F      |  *      | Invalid scope       |
| A, B, C |        | A       | A / Invalid scope   |
|         |        | *       | Invalid scope       |
| A,B, C  | A, B   |         | A,B / Invalid scope |

For examples that are defined with / (A / Invalid scope) - exact behavior would be defined through configuration. If _strict_ scope behaviour is set to _true_ Invalid scope exception is thrown, otherwise scope is inherited from client / storage.

**Comment by spideyfusion** [comment]
Scope management has been revamped in https://github.com/trikoder/oauth2-bundle/pull/24.
