### ISSUE TITLE
Symfony 4.3 deprecations

### ISSUE THREAD

**Issue by rbaarsma** [trikoder/oauth2-bundle#71]
Upgrading to Symfony 4.3 gives the following deprecation errors:

The "Trikoder\Bundle\OAuth2Bundle\Event\ScopeResolveEvent" class extends "Symfony\Component\EventDispatcher\Event" that is deprecated since Symfony 4.3, use "Symfony\Contracts\EventDispatcher\Event" instead.

The "Trikoder\Bundle\OAuth2Bundle\Event\UserResolveEvent" class extends "Symfony\Component\EventDispatcher\Event" that is deprecated since Symfony 4.3, use "Symfony\Contracts\EventDispatcher\Event" instead.

The "Trikoder\Bundle\OAuth2Bundle\Security\Firewall\OAuth2Listener" class implements "Symfony\Component\Security\Http\Firewall\ListenerInterface" that is deprecated since Symfony 4.3, turn listeners into callables instead.

**Comment by X-Coder264** [comment]
We are currently supporting the latest SF LTS version which is 3.4 and we'll continue to support it during the 2.x life-cycle of this bundle. We can't "fix" these deprecations until the minimum required SF version for the bundle is 4.3. For the 3.0 major version we will probably drop support for SF 3.4 as by that time the latest LTS will be 4.4 and then these deprecations will be fixed.

**Comment by rbaarsma** [comment]
:+1: I understand. I think it's wise to start a 3.0 version for SF 4+. I think that's how most bundles are handling it. You could label this issue as 3.0 version

**Comment by X-Coder264** [comment]
Closed by https://github.com/trikoder/oauth2-bundle/pull/150
