### ISSUE TITLE
[Easy pick] All final classes must have an interface

### ISSUE THREAD

**Issue by Nyholm** [trikoder/oauth2-bundle#76]
We need this to be able to mock and tests our code.

**Comment by X-Coder264** [comment]
I don't think we should blindly add interfaces to all final classes in the bundle just for some "test" purposes. For example I don't see any value in adding an interface for the `UserConverter` class. I don't see the possibility of there being another implementation that justifies an interface (or it's very unlikely at least) nor does this implementation do any I/O or database calls etc which means doing `new UserConverter()` in your tests is just fine if you ask me.

**Comment by Nyholm** [comment]
No, not "blindly". Final classes that are not "internal" should have an interface. 

Speaking of your example of `UserConverter`: 
I like the `OauthAuthorizationController` but I need do to some modifications to it. So I copied that class to my namespace and did my modifications. (Everything is perfect.) However, when I write unit tests from my new controller class I cannot mock its dependencies. That is reason 1 why we need an interface. 

Reason 2 is that `OauthAuthorizationController` has dependency on a concrete class. That violates the dependency inversion principle. 

---------

You are probably correct when you say that there will most likely not be an other implementation of the `UserConverter`. However, adding an interface to be more correct will guarantee future proof code.

**Comment by alexspark21** [comment]
Yep, I think we have to set UserConverterInterface,  because I have to have possibility override UserConverter and implement my logic

**Comment by janvernieuwe** [comment]
I just ran into a situation where a `ScopeInterface` would have been nice.
When retrieving scopes from a custom system you could just implement it and return them.

**Comment by X-Coder264** [comment]
I think everything here that was mentioned is solved. Feel free to open a new issue if there are still things that need to be improved.
