### ISSUE TITLE
[Easy pick] Use FQCN for service ids

### ISSUE THREAD

**Issue by Nyholm** [trikoder/oauth2-bundle#77]
All services should be using FQCN (fully qualified class names (namespace + class)) as their service ids. 

We could add aliases if we really wanted to keep our sf3.x standard. 

```yaml
    Trikoder\Bundle\OAuth2Bundle\Converter\UserConverter: '@trikoder.oauth2.converter.user_converter'
```

**Comment by X-Coder264** [comment]
Fixed by https://github.com/trikoder/oauth2-bundle/pull/80

😃
