### ISSUE TITLE
composer test failed

### ISSUE THREAD

**Issue by kpn13** [trikoder/oauth2-bundle#78]
Hi,

I tried to install the projet using your instructions (branch master) : 

dev/bin/docker-compose build --build-arg PHP_VERSION=7.3
dev/bin/php composer install
dev/bin/php composer test

But the tests failed with this message : 

`Fatal error: Cannot make static method Symfony\Bundle\FrameworkBundle\Test\WebTestCase::getClient() non static in class Trikoder\Bundle\OAuth2Bundle\Tests\Acceptance\DeleteClientCommandTest in /app/src/Tests/Acceptance/DeleteClientCommandTest.php on line 73

Call Stack:
    0.0001     403584   1. {main}() /app/src/vendor/phpunit/phpunit/phpunit:0
    0.0046    1102840   2. PHPUnit\TextUI\Command::main() /app/src/vendor/phpunit/phpunit/phpunit:61
    0.0047    1102952   3. PHPUnit\TextUI\Command->run() /app/src/vendor/phpunit/phpunit/src/TextUI/Command.php:160
    0.0047    1102952   4. PHPUnit\TextUI\Command->handleArguments() /app/src/vendor/phpunit/phpunit/src/TextUI/Command.php:168
    0.0095    1486096   5. PHPUnit\Util\Configuration->getTestSuiteConfiguration() /app/src/vendor/phpunit/phpunit/src/TextUI/Command.php:909
    0.0333    2806504   6. PHPUnit\Util\Configuration->getTestSuite() /app/src/vendor/phpunit/phpunit/src/Util/Configuration.php:909
    0.0356    2821184   7. PHPUnit\Framework\TestSuite->addTestFiles() /app/src/vendor/phpunit/phpunit/src/Util/Configuration.php:1044
    0.0628    3275824   8. PHPUnit\Framework\TestSuite->addTestFile() /app/src/vendor/phpunit/phpunit/src/Framework/TestSuite.php:439
    0.0628    3275824   9. PHPUnit\Util\FileLoader::checkAndLoad() /app/src/vendor/phpunit/phpunit/src/Framework/TestSuite.php:347
    0.0629    3276032  10. PHPUnit\Util\FileLoader::load() /app/src/vendor/phpunit/phpunit/src/Util/FileLoader.php:47`

I suppose the issue comes from me but I can't find what I did wrong, could you help me ?

**Comment by HypeMC** [comment]
Hi, the problem is happens cause composer installs the latest Symfony version, which is 4.3. Until we add support for this version, please try it with 4.2: `dev/bin/php composer require symfony/symfony:~4.2 --no-update`.

**Comment by kpn13** [comment]
Ok thank you !
