### ISSUE TITLE
Getting `unsupported_grant_type` due to `$request->getParsedBody()` being empty

### ISSUE THREAD

**Issue by warrenca** [trikoder/oauth2-bundle#89]
I've seen some issues raised with regards to `unsupported_grant_type` but it didn't solve my problem so I posted another one.

Composer
```
"symfony/symfony": "3.4.*",
"trikoder/oauth2-bundle": "^1.1",
```

Request
```
curl --request POST \
  --url https://localhost:8080/oauth/token \
  --header 'content-type: application/json' \
  --data '{
    "grant_type": "password",
    "client_id": "CLIENT_ID",
    "client_secret": "SECRET",
    "username": "user@email.com",
    "password": "password"
}' --insecure
```

Response
```
{"error":"unsupported_grant_type","message":"The authorization grant type is not supported by the authorization server.","hint":"Check that all required parameters have been provided"}
```

I saw the cause in `vendor/league/oauth2-server/src/Grant/AbstractGrant.php` where `(array) $request->getParsedBody()` returns `null` anywhere it's used. Changing it to `(array) json_decode($request->getBody())` returns the JSON values as array. I know, it's a dependency of this package but I'm just checking if anyone got a solution for this or maybe I'm doing the request wrong.

**Comment by warrenca** [comment]
For some reason, `content-type: application/x-www-form-urlencoded` works and not `application/json`
```
curl --request POST \
  --url https://localhost:8080/oauth/token \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data client_id=CLIENT_ID \
  --data client_secret=SECRET \
  --data grant_type=password \
  --data 'username=user@email.com' \
  --data 'password=mypassword'
```

**Comment by ajgarlag** [comment]
I think the reason is in [Section 4.1.3](https://tools.ietf.org/html/rfc6749#section-3.1) from RFC 6749:

> The client makes a request to the token endpoint by sending the
   following parameters using the "application/x-www-form-urlencoded"
   format per Appendix B with a character encoding of UTF-8 in the HTTP
   request entity-body

If you need to support `application/json` content type, maybe you can write a custom grant type.

**Comment by warrenca** [comment]
@ajgarlag Thanks for that info. If I am going to write my custom grant type, can I do it on top of trikoder/oauth2-bundle or would you know if there is a configuration where I can attach that custom grant type?

**Comment by ajgarlag** [comment]
I think this bundle does not support custom grant type. Maybe you can PR to support it.

**Comment by X-Coder264** [comment]
I'm not sure that even the League Oauth2 server itself supports adding custom grant types. If there is a possibility for that then we welcome any PR that would implement that in our bundle.

**Comment by X-Coder264** [comment]
I took a look in the League code, it is possible to do this. We will follow the progress for that through issue https://github.com/trikoder/oauth2-bundle/issues/143
